version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk-network

  kibana:
    image: kibana:8.14.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  logstash:
    image: logstash:8.14.3
    container_name: logstash
    ports:
      - "5000:5000/tcp"
      - "5044:5044/tcp"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  filebeat:
    image: elastic/filebeat:8.14.3
    container_name: filebeat
    user: root
    restart: unless-stopped
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/nginx:/var/log/nginx:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - filebeat-data:/usr/share/filebeat/data
    depends_on:
      - logstash
    networks:
      - elk-network

  metricbeat:  # НОВЫЙ СЕРВИС
    image: elastic/metricbeat:8.14.3
    container_name: metricbeat
    user: root
    restart: unless-stopped
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - metricbeat-data:/usr/share/metricbeat/data
    depends_on:
      - elasticsearch
    networks:
      - elk-network

volumes:
  es_data:
    driver: local
  filebeat-data:
    driver: local
  metricbeat-data:  # Новый volume для Metricbeat
    driver: local

networks:
  elk-network:
    driver: bridge
